
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: create html artifact
          command: |
            . venv/bin/activate
            mkdir html-artifacte-report
            jupyter nbconvert --execute hw1.ipynb
            mv hw1.html html-artifacte-report/hw1.html

      - store_artifacts:
          path: html-artifacte-report
          destination: html-artifacte-report