
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: download_data_and_submit_to_kaggle
          command: |
            . venv/bin/activate
	    cd ~/
	    pip install kaggle
            mkdir .kaggle
            cd .kaggle
            echo $kaggle_api > kaggle.json
	    kaggle competitions download titanic
            jupyter nbconvert --execute hw2.ipynb
            kaggle competitions submit titanic -f titanic.csv -m "submission_from_circle_ci"

      - store_artifacts:
          path: html-artifacte-report
          destination: html-artifacte-report